<?php

namespace lostBook\lostBookUserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MediaUtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaUtilisateurRepository extends EntityRepository
{
}
