_lostbook_homepage:
    path:     /
    defaults: { _controller: lostBookBundle:Default:index }
_lostbook_nouvelle_annonce:
    path:     /new/found
    defaults: { _controller: lostBookBundle:Default:nouvelleAnnonce }

_lostbook_new_lost:
    path:     /new/lost
    defaults: { _controller: lostBookBundle:Default:newLost }

_lostbook_details_annonce:
    path:     /detailsAnnonce/{idAnnonce}
    defaults: { _controller: lostBookBundle:Default:detailsAnnonce }
    
_lostbook_nouveau_commentaire_annonce_action:
    path: /commentaireAnnonce
    defaults: { _controller: lostBookBundle:AJAX:nouveauCommentaireAnnonce }
    options:
        expose: true
_lostbook_delete_image_annonce_action:
    path: /deleteImageAnnonce/{idAnnonce}/{idMedia}
    defaults: { _controller: lostBookBundle:AJAX:deleteImageAnnonce }
    options:
        expose: true
        
_lostbook_delete_image_espace_action:
    path: /deleteImageEspace/{idEspace}/{idMedia}
    defaults: { _controller: lostBookBundle:AJAX:deleteImageEspace }
    options:
        expose: true
        
_lostbook_update_annonce:
    path: /annonces/miseAJour/{idAnnonce}
    defaults: { _controller: lostBookBundle:Default:updateAnnonce }
   
_lostbook_update_espace:
    path: /espaces/miseAJour/{idEspace}
    defaults: { _controller: lostBookBundle:Espace:updateEspace }
 
_lostbook_delete_espace: 
    path: /espaces/delete/{idEspace}
    defaults: { _controller: lostBookBundle:Espace:deleteEspace }
    
_lostbook_saisie_code_createur:
    path: /security/code/{idAnnonce}
    defaults: { _controller: lostBookBundle:Security:saisieCodeCreateur }
    
_lostbook_delete_annonce: 
    path: /annonces/delete/{idAnnonce}
    defaults: { _controller: lostBookBundle:Default:deleteAnnonce }
    
## Espaces

_lostbook_espaces_index:
    path: /espaces
    defaults: { _controller: lostBookBundle:Espace:index }
    
_lostbook_nouvel_espace:
    path: /nouvelEspace
    defaults: { _controller: lostBookBundle:Espace:nouvelEspace }
    
_lostbook_details_espace:
    path: /detailsEspace/{idEspace}
    defaults: { _controller: lostBookBundle:Espace:detailsEspace }
 
_contact_annonceur:
     path: /contact
     defaults: { _controller: lostBookBundle:AJAX:contacterAnnonceur}
     options:
         expose: true
    
    
 ## Automatics tasks
 
_rtc_matching:
     path: /matching
     defaults: { _controller: AutomaticTasks:rTCMatching }
     options:
         expose: true
    

## Administration
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    
    
_espaces_for_ville:
    path:  /espacesForville/{idVille}         
    defaults: { _controller: lostBookBundle:AJAX:getEspacesForVille }
    options:
        expose: true
    
annonces:
    type:   rest
    resource:   lostBook\lostBookBundle\Controller\API\AnnonceController
    
villes:
    type:   rest
    resource: lostBook\lostBookBundle\Controller\API\VilleController
    
_faqs:
    path: /faqs
    defaults: { _controller: lostBookBundle:Default:faqs }
   
   
   