# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

#services:
#    kernel.listener.upload_listener:
#        class: lostBook\lostBookBundle\EventListener\UploadListener
#        tags:
#            - { name: kernel.event_listener, event: oneup_uploader.pre_upload, method: preUpload }

services:
   
    lostbook.userbundle.user_edit:
        class: lostBook\lostBookUserBundle\Listener\ProfileEditListener
        arguments: [@service_container]
        tags:
            - { name: kernel.event_subscriber }
   
    lostbook.userbundle.user_register:
        class: lostBook\lostBookUserBundle\Listener\RegistrationListener
        arguments: [@service_container]
        tags:
            - { name: kernel.event_subscriber }
    kernel.listener.upload_listener:
        class: lostBook\lostBookBundle\EventListener\RedirectionConnexionListener
        arguments: [@service_container,@session]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
            
    app.form.registration:
        class: lostBook\lostBookUserBundle\Form\Type\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
    app.form.profile:
        class: lostBook\lostBookUserBundle\Form\Type\ProfileEditType
        tags:
            - { name: form.type, alias: app_user_profile }
            
    admin.ville:
        class: lostBook\lostBookBundle\Admin\VilleAdmin
        arguments: [~, lostBook\lostBookBundle\Entity\Ville, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Ville }
    
    admin.espace:
        class: lostBook\lostBookBundle\Admin\EspaceAdmin
        arguments: [~, lostBook\lostBookBundle\Entity\Espace, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Espace }
    admin.annonce:
        class: lostBook\lostBookBundle\Admin\AnnonceAdmin
        arguments: [~, lostBook\lostBookBundle\Entity\Annonce, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Annonce }
            
    admin.categorie:
        class: lostBook\lostBookBundle\Admin\CategorieAdmin
        arguments: [~, lostBook\lostBookBundle\Entity\Categorie, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Categorie }
            