<?php

namespace rTC\rTCBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TestProprietaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestProprietaireRepository extends EntityRepository
{
}
