<?php

namespace lostBook\lostBookBundle\Repository;

use Doctrine\ORM\EntityRepository;
use lostBook\lostBookBundle\Entity\RechercheAnnonces;

/**
 * AnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceRepository extends EntityRepository
{
    public function getAllAnnonces() {
              
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT a,m,"
                                  . " FROM lostBookBundle:Annonce a "
                                  . "JOIN a.medias");
        $annonces = $query->getResult();  
        
        return $annonces;
    }
    
    public function getAnnonceById($id)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT a,m,u FROM lostBookBundle:Annonce a "
                                  . "JOIN a.medias m JOIN a.utilisateur u "
                                  . "WHERE a.id = :id");
        $query->setParameter('id', $id);
        
        try
        {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $ex) {
            
            return null;
        }
        
    }
    
    public function getResultatRecherche(RechercheAnnonces $recherche)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT a,m"
                                  . " FROM lostBookBundle:Annonce a "
                                  . "JOIN a.medias m");
        $annonces = $query->getResult();  
        
        return $annonces;
        
    }
}
