<?php

namespace lostBook\lostBookBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EspaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EspaceRepository extends EntityRepository
{
    public function findByVille($idVille) {
              
        
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT e.id, e.nom FROM lostBookBundle:Espace e WHERE e.ville = :idVille");
        $query->setParameter('idVille',$idVille);
        $espaces = $query->getResult();  
        
        return $espaces;
    }
}
