<?php

namespace lostBook\lostBookBundle\Repository;

use Doctrine\ORM\EntityRepository;
use lostBook\lostBookBundle\Entity\RechercheEspaces;

/**
 * EspaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EspaceRepository extends EntityRepository
{
    public function findByVille($idVille) {
              
        
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT e.id, e.nom FROM lostBookBundle:Espace e WHERE e.ville = :idVille");
        $query->setParameter('idVille',$idVille);
        $espaces = $query->getResult();  
        
        return $espaces;
    }
    
    public function findAll()
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT e"
                                  . " FROM lostBookBundle:Espace e "
                                  . " where e.etat = '0' order by e.id desc");
        $annonces = $query->getResult();  
        
        return $annonces;  
    }
    
    public function getResultatRecherche(RechercheEspaces $recherche)
    {
        $em = $this->getEntityManager();
        if($recherche->getEspace() != null)
        {
        $query = $em->createQuery("SELECT e"
                                  . " FROM lostBookBundle:Espace e "
                                  . "where e.id = :idEspace");
        $query->setParameter('idEspace',$recherche->getEspace()->getId());
        $espaces = $query->getResult();
        }
        else if($recherche->getVille() != null)
        {
           $query = $em->createQuery("SELECT e"
                                  . " FROM lostBookBundle:Espace e "
                                  . "WHERE e.ville = :ville"); 
           $query->setParameter('ville',$recherche->getVille()->getId());
           $espaces = $query->getResult();
        }
        
        else
        {
            $espaces = array();
        }
        return $espaces;
        
    }   
   
}
