<?php

namespace lostBook\lostBookBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MembreEspaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembreEspaceRepository extends EntityRepository
{
}
