<?php

namespace lostBook\lostBookBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProfilEspaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfilEspaceRepository extends EntityRepository
{
}
